# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 6f9840cfd05d0b673a58bf49e9a027d1ca32fd6b7573ea465071890ee7448026de8f533c679158f0b63349b3f737711e847063075b390985879d63faea31b9f9

test:
  domain_name: example.com 
  secret_key_base: 0e816a95a20bbc41ab9d11b42e31c597d1d3956de6a981d1630112e3fc7a8dd59857e823424fc991a79b4dc04f49e97494bdb473f46a44ddeea824b22e2cb618

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
